### ISSUE TITLE
StopIteration Error

### ISSUE THREAD

**Issue by rohanddave** [insidesherpa/JPMC-tech-task-2#208]
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

**Comment by Robot-dev11** [comment]
File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

**Comment by vamshi04** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2/issues/181#issuecomment-649743299
