### ISSUE TITLE
serve.py and npm is not starting  I am facing the following issue

### ISSUE THREAD

**Issue by Achyut13** [insidesherpa/JPMC-tech-task-2#235]
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

**Comment by rajkumar-telu** [comment]
Don't execute directly within the folder, execute it outside datafeed folder using python datafeed/server.py (if python 3.x then server3.py)

**Comment by yashsontakke** [comment]
> python3 datafeed/server3.py
worked !!!!
thnx ..
