### ISSUE TITLE
File "server3.py", line 244, in __init__     self._sim_start, _, _  = next(self._data_1) StopIteration

### ISSUE THREAD

**Issue by ShresthSrivastava** [insidesherpa/JPMC-tech-task-2#238]
F:\J.P. Morgan Internship\JPMC-tech-task-2-PY3\datafeed>python3 server3.py
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

![error](https://user-images.githubusercontent.com/59231752/85401426-9d1ed280-b577-11ea-88b8-b98504b14fae.PNG)

**Comment by goku9313** [comment]
Did you figure out the solution if yes please share how

**Comment by vamshi04** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2/issues/181#issuecomment-649743299

**Comment by mitulgupta72** [comment]
#change in file server3.py 
#class app 
 # Ensure _sim_start is initialized with a valid value
        while True:
            try:
                self._sim_start, _, _ = next(self._data_1)
                break
            except StopIteration:
                # If _data_1 is empty, try again with the next data point
                pass
