### ISSUE TITLE
UNCAUGHT EXCEPTION

### ISSUE THREAD

**Issue by HarounaZoundi** [insidesherpa/JPMC-tech-task-2#39]
m\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\thale\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\thale\Desktop\Documents\Brooklyn College\Chase Virtual Internship\JPMC-tech-task-2\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0

**Comment by pemesie** [comment]
Hey,
I am having this issue when I run npm install. I am using windows.


prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\pemesie\Documents\UNL\UNL\job\JPMorgang\virtualInternship\task2\JPMC-tech-task-2\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\pemesie\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\pemesie\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pemesie\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\pemesie\Documents\UNL\UNL\job\JPMorgang\virtualInternship\task2\JPMC-tech-task-2\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pemesie\AppData\Roaming\npm-cache\_logs\2020-04-16T00_25_16_087Z-debug.log

C:\Users\pemesie\Documents\UNL\UNL\job\JPMorgang\virtualInternship\task2\JPMC-tech-task-2>type python2.7
The system cannot find the file specified.

C:\Users\pemesie\Documents\UNL\UNL\job\JPMorgang\virtualInternship\task2\JPMC-tech-task-2>python2.7
'python2.7' is not recognized as an internal or external command,
operable program or batch file.

**Comment by VaddadiSaiRahul** [comment]
@HarounaZoundi  @pemesie 
Guys I somehow resolved this issue in linux but before I was doing in Windows. but I think the same applies in Windows too.

**The reason for this error is your npm is not mapped to python 2.x or 3.x**. make sure you map the
python command npm uses to python 2.7.x. The problem is also listed in the pdf file of task2 from page 88.

I got through this by setting npm config set python /path/to/executable/python
where /path/to/executable/python is the directory where the python2.7.x binary is, for example in /usr/bin/python usually in linux/mac or C:\Python27 for Windows

Then my problem cleared. This is for linux version , follow the windows version to set path of npm to python.

THis must solve the problem

**Comment by dheerajodha** [comment]
Hi @HarounaZoundi as solution suggested above,
If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by devinl8672** [comment]
Could someone post the commands you ran because I'm still confused and I have no clue how to solve it.
