### ISSUE TITLE
UNCAUGHT EXCEPTION DURING NPM INSTALL

### ISSUE THREAD

**Issue by harshb1995** [insidesherpa/JPMC-tech-task-2#40]
I have Windows OS. I have followed the steps correctly till npm install and i didnt get any error. But on npm install i am getting UNCAUGHT EXCEPTION---
ERROR on CONSOLE IS ---

> bufferutil@3.0.5 install C:\Users\Harsh\JPMC-tech-task-2\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\Harsh\JPMC-tech-task-2\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Harsh\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Harsh\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Harsh\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Harsh\JPMC-tech-task-2\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\Harsh\JPMC-tech-task-2\node_modules\fsevents\node_modules'
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Harsh\AppData\Roaming\npm-cache\_logs\2020-04-18T08_18_37_670Z-debug.log

How to resolve it. Because of this i am stuck in task2

**Comment by harshb1995** [comment]
![image](https://user-images.githubusercontent.com/10399296/79632779-0c92d300-817f-11ea-81cd-2eea723875c5.png)

**Comment by riturajkush** [comment]
I am also facing the same issue. there is absence of MSBuild.exe file

**Comment by harshb1995** [comment]
Hi @riturajkush . Did you figure out how this can be resolved?

**Comment by VaddadiSaiRahul** [comment]
@harshb1995 Bro I somehow resolved this issue in linux but before I was doing in Windows. but I think the same applies there.

The reason for this error is your npm is not mapped to python 2.x or 3.x.  make sure you map the 
python command npm uses to python 2.7.x. The problem is also listed in the pdf file of task2 from page 88.

I got through this by setting **npm config set python /path/to/executable/python**
 where /path/to/executable/python is the directory where the python2.7.x binary is, for example in /usr/bin/python usually in linux/mac or C:\\Python27 for Windows

**Comment by riturajkush** [comment]
![isuue](https://user-images.githubusercontent.com/33595729/80314793-35673800-8811-11ea-8730-1573ebc081b7.png)

These are things I tried and still got this error

1) Did changes in the environment variable to set python 2.7 as path
2) Used JPMC tech task repo which is for python 2.7
3) node -v is 11.0.0
4) npm -v is 6.4.1

**Comment by VaddadiSaiRahul** [comment]
@riturajkush 
This problem arises mainly because of not setting the path. If you have set the path correctly then it must work.

I suggest u check the following again:
1. Check if your default python version is 2.7 or 3.x.
2. Since u have used JPMC-tech-task-2 for Python 2.7, check if npm is configured to python's path.
    Command is : npm config set /path/to/executables; in windows it is C:\\Python27. This must work
3. Check if your Python path is set in environment variables. Go to System variables and check if Python 2.7 or whatever version u are using for this task is set there.

**Comment by dheerajodha** [comment]
Hi @harshb1995 
If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by kennyklee123** [comment]
@riturajkush  hey man I am currently in the same boat as your error from April 26, did you end up finding a fix?

**Comment by devinl8672** [comment]
I am still having the issue after I ran npm config set python C:\Python27. Could anyone help?

**Comment by owen-runge** [comment]
> @harshb1995 Bro I somehow resolved this issue in linux but before I was doing in Windows. but I think the same applies there.
> 
> The reason for this error is your npm is not mapped to python 2.x or 3.x. make sure you map the python command npm uses to python 2.7.x. The problem is also listed in the pdf file of task2 from page 88.
> 
> I got through this by setting **npm config set python /path/to/executable/python** where /path/to/executable/python is the directory where the python2.7.x binary is, for example in /usr/bin/python usually in linux/mac or C:\Python27 for Windows
> 
> Then my problem cleared. This is for linux version , follow the windows version to set path of npm to python.
> 
> THis must solve the problem

I set my path to my python3.exe file and have the following error:
![JPM-Perspective-Error](https://user-images.githubusercontent.com/88351125/178074540-6850619e-5a8b-4b70-8d5a-4bc505d6e508.png)
Can someone help me with this?
